DELETE https://{{NVIM_REST_AZU_DEVOPS_VSSPS_ORG_URL}}/_apis/graph/groups/aadgp.Uy0xLTktMTU1MTM3NDI0NS0xMjA0NDAwOTY5LTI0MDI5ODY0MTMtMjE3OTQwODYxNi0zLTM2MDMyMjE3ODQtMzMzODYyNzkxOS0yMjAxNDAwMDMwLTEyODA1NDQwMjY?api-version=6.0-preview.1
Authorization: Basic {{NVIM_REST_AZU_API_BASIC_AUTH}}
